version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: AsisyaDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AsisyaDb;Username=postgres;Password=postgres123
      - Jwt__Key=MySecretKeyForJWTTokenGeneration123456789012345
      - Jwt__Issuer=AsisyaApi
      - Jwt__Audience=AsisyaApi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: